- name: Configure application
  hosts: all
  become: true
  become_method: sudo
  vars:
      repository_url: https://github.com/kevinlondon/flask-hello-world.git
      repository_path: /home/vagrant/flask-hello-world

  tasks:
    - name: Install packages
      apt: update_cache=yes name={{ item }} state=present
      with_items:
        - git
        - python-pip
        - nginx

    - name: Clone repository
      git: repo='{{ repository_url }}' dest='{{ repository_path }}'

    - name: Install requirements
      pip: requirements='{{ repository_path }}/requirements.txt'

    - name: Copy Upstart configuration
      template: src=hello-world.conf.j2 dest=/etc/init/hello-world.conf

    - name: Make sure our server is running
      service: name=hello-world state=started

    - name: Copy nginx configuration
      template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
      notify:
        - reloaded nginx

    - name: Remove any default sites
      file: path=/etc/nginx/sites-enabled/default state=absent

    - name: Make sure nginx is running
      service: name=nginx state=started

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
